plugins {
    id 'com.android.library'
}

android {
    namespace 'com.reveny.imguimod'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    externalNativeBuild {
        cmake {
            cppFlags "-std=c++17 -fPIC"
        }
    }

    ndk {
        abiFilters 'arm64-v8a'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
