plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.reveny.modmenu'
    compileSdk 34

    defaultConfig {
        applicationId "com.reveny.modmenu"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    
    externalNativeBuild {
        cmake {
            cppFlags "-std=c++17"
        }
    }
    
    buildFeatures {
        viewBinding true
    }
    
    ndkVersion '25.2.9519653'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.github.reveny:Dobby:1.0'
    implementation 'com.github.MJx0:KittyMemory:2.0'
}
