#include "TouchHook.h"
#include "HookEngine.h"
#include <android/input.h>
#include <android/looper.h>
#include <android/looper_pollfd.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper_messagequeue.h>
#include <android/looper_threadsafe.h>
#include <android/looper_wakeup.h>
#include <android/looper_file.h>
#include <android/looper
